### ISSUE TITLE
Remove role from member.

### ISSUE THREAD

**Issue by KAMIL0024** [iBlitzkriegi/Vixio#225] opened 2019-11-27 05:36 UTC
**Describe the bug**
Remove role from member is not work.

**Information**
Skript version: dev37
Vixio version: 2.0.3
Minecraft Version: spigot 1.12.2

**Screenshots**
https://i.fratikbot.pl/ue9OhPz.mp4

**Comment by mc1a3** [comment] 2019-12-05 12:49
Duplicate of #210

**Closed** 2019-12-12 01:37 UTC
