### ISSUE TITLE
Cannot use event-member has permission.

### ISSUE THREAD

**Issue by EnderDev** [iBlitzkriegi/Vixio#147] opened 2018-12-26 16:47 UTC
**Describe the bug**
Cannot use event-member has permission.

**To Reproduce**
1. Use the following `if event-member has permission manage message:`

**Expected behavior**
Should work, and I have it add the ❌ emoji to the message if they dont have permission, however it does now do that and gives this error: `> [17:44:49 ERROR]: can't understand this condition: 'event-member has permission manage messages in event-channel' (admin.sk, line 70: if event-member has permission manage messages in event-channel:')
> [17:44:49 ERROR]: can't understand this condition: 'event-member does not have permission manage messages in event-channel' (admin.sk, line 85: if event-member does not have permission manage messages in event-channel:')`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by GamingGeek** [comment] 2018-12-26 16:50
Check pinned messages in `#support` for all the permission values. It's `message manage` by the way

**Comment by EnderDev** [comment] 2018-12-27 12:38
This doesn't work at all, even when I specify the correct values.

**Comment by iBlitzkriegi** [comment] 2018-12-30 01:59
Due to a lack of evidence and the fact that many bots use this daily, I'm closing this issue. You may seek more support in the Vixio discord, but seeing as this isn't a legitimate bug this issue will be closed. 
Side note, this could be caused by about anything, Vixio not starting, outdated skript versions causing problems, anything, outdated Vixio version, etc.

**Closed by iBlitzkriegi** 2018-12-30 01:59 UTC

**Comment by EnderDev** [comment] 2018-12-31 11:02
> 
> 
> Due to a lack of evidence and the fact that many bots use this daily, I'm closing this issue. You may seek more support in the Vixio discord, but seeing as this isn't a legitimate bug this issue will be closed.
> Side note, this could be caused by about anything, Vixio not starting, outdated skript versions causing problems, anything, outdated Vixio version, etc.

Hi I cannot "seek" support as I am muted in the Discord thank you for your time.

**Comment by KingAlterIV** [comment] 2018-12-31 18:17
Not our fault you got muted. ¯\_(ツ)_/¯

**Comment by EnderDev** [comment] 2018-12-31 19:16
I am only pointing out that @iBlitzkriegi said I should seek support in the Discord.
