### ISSUE TITLE
Offline player parsing v2

### ISSUE THREAD

**Issue by blizma** [iBlitzkriegi/Vixio#180] opened 2019-06-06 02:17 UTC
**Describe the bug**
Whenever I try to do this:
```vbs
command /test:
	trigger:
		set {_player} to "%player%" parsed as offlineplayer
		if {_player} is online:
			send "yes"
		else:
			send "no"
```
with Vixio, it sends no.
without Vixio, it sends yes.

**To Reproduce**
```vbs
command /test:
	trigger:
		set {_player} to "%player%" parsed as offlineplayer
		if {_player} is online:
			send "yes"
		else:
			send "no"
```

**Expected behavior**
It's supposed to say "yes" as the player is online.

**Screenshots**
1) http://ralsei-pfp.is-super.ga/y/1ihhl.png 
2) http://ralsei-pfp.is-super.ga/y/0f988.png

1 is before I deleted Vixio to test. (I parsed the player as a player initially, I then parsed the player as an offline player.)
2 is after I deleted Vixio.

**Additional context**
I use the same (not exactly the same but still) code in my other Skripts, this messes up my Skripts whenever I install Vixio.

**Comment by blizma** [comment] 2019-06-06 02:19
I can provide more context/proof if needed.

**Comment by iBlitzkriegi** [comment] 2019-06-06 02:48
![image](https://user-images.githubusercontent.com/17624546/59003452-03f21200-87e4-11e9-9751-6fe8e4819e5e.png)

**Comment by blizma** [comment] 2019-06-06 02:59
>I parsed the player as a player initially, I then parsed the player as an offline player.

**Comment by iBlitzkriegi** [comment] 2019-06-06 03:01
I ran the provided code that you said had issues, and was unable to reproduce?

**Comment by blizma** [comment] 2019-06-06 03:04
It’s been happening with other people I know too, I’ll provide a screenshot later when I reproduce it

**Comment by blizma** [comment] 2019-06-06 03:29
- Tried this on a pure server with only Skript, TacoSpigot, and Vixio.
- Did the same Skript, doesn't work correctly, returns no.

**Comment by blizma** [comment] 2019-06-06 03:42
- Tried this on Spigot, no dice.

**Comment by iBlitzkriegi** [comment] 2019-06-06 04:06
This isn't reproducible so there isn't anything I can do with this, it works perfectly fine for me. Could try the Vixio build floating around in #general in the Vixio Discord but, otherwise this won't be fixed.

**Closed by iBlitzkriegi** 2019-06-06 04:06 UTC
