### ISSUE TITLE
Error with pin syntax

### ISSUE THREAD

**Issue by Kuro001** [iBlitzkriegi/Vixio#161] opened 2019-02-13 14:00 UTC
When I use syntax `pin %messages% [with %bot/string%]`
Example:
```
reply with "asd" and store it in {_msg}
pin {_msg}
```
In dm, give me this error: https://hastebin.com/redexuduno.md
In guild, give me this error: https://hastebin.com/otirowecuv.md

**Comment by iBlitzkriegi** [comment] 2019-02-25 03:08
I'm not able to reproduce this, you could be running an outdated vixio version. Or maybe I had fixed this recently and forgotten to close this issue? Whatever it is, I'm pretty sure this is no longer an issue.

**Comment by iBlitzkriegi** [comment] 2019-02-25 03:09
To append to that, it was fixed here; https://github.com/iBlitzkriegi/Vixio/commit/4bb4698b015ea95d056eec61170501475331d624

**Closed by iBlitzkriegi** 2019-02-25 03:08 UTC
Labels: bug
